version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Change this based on your runtime version
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt

  build:
    commands:
      - echo Building the Lambda deployment package
      - zip -r lambda-function-1.zip lambda_function.py  # Adjust the path if needed

artifacts:
  files:
    - lambda-function-1.zip  # This will be the artifact produced by CodeBuild


