version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      # Add any dependency installation commands here, if needed
  pre_build:
    commands:
      - echo Preparing to package Lambda function
  build:
    commands:
      - echo Packaging Lambda function
      - zip -r lambda-function.zip lambda_function.py
artifacts:
  files:
    - lambda-function.zip

