version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Change this based on your runtime version
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt

  build:
    commands:
      - echo Building the Lambda deployment package
      - zip -r lambda-function.zip lambda_function.py  
      - aws s3 cp lambda-function.zip s3://saadi-lambda/  


